accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [

    path('signup/', views.SignUp.as_view(), name='signup')

]

game/urls.py
from django.urls import path
from .views import record_score
from .views import GameHistory, GamePlay, PlayerHistory
from django.conf import settings
from django.conf.urls.static import static

app_name = 'game'

urlpatterns = [

    path('game_history/', GameHistory.as_view(), name = "game_history"),
    path('previous_scores/<id>/', PlayerHistory.as_view(), name = "player_history"),
    path('game_play/', GamePlay.as_view(), name = "game_play" ),
    path('record_score', record_score, name = "record_score")

] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

game_website1_1/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Homepage, Logout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', Homepage.as_view(), name = 'home'),
    path('logout', Logout.as_view(), name = 'logged_out'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('game/', include('game.urls', namespace='game')),

]

posts/urls.py
from django.urls import path

from .import views

app_name = 'posts'

urlpatterns = [

    path('create_post/', views.PostCreateView.as_view(), name = 'create_post'),
    path('post_list/', views.PostListView.as_view(), name= 'post_list'),

]

accounts/models.py
from django.db import models

# Create your models here.

game/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Game(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField()
    time = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.score

posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import datetime
from django.urls import reverse_lazy, reverse

User = get_user_model()

# Create your models here.
class Posts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    post_text = models.TextField()
    time = models.DateTimeField(auto_now=True)
    # def save(self, *args, **kwargs):
    #     self.time = datetime.now()
    #     super(Posts, self).save()

    def get_absolute_url(self):
        return reverse('posts:post_list')

    def __str__(self):
        return self.title

posts/forms.py
from django.forms import ModelForm
from .models import Posts

class PostForm(ModelForm):
    class Meta:
        model = Posts
        fields = ['title', 'post_text']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.
class SignUp(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

game/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView,DetailView, ListView
from .models import Game

# Create your views here.
def record_score(request):

    score = request.POST['score']

    try:
        game = Game.objects.create(
            user = request.user,
            score = score,
        )
        game.save()

        response = {
            'status':1,
            'message':'Game saved'
        }
    except Exception as e:
        response = {
            'status': 0,
            'message':'Something went wrong - ' + str(e)
        }
    return JsonResponse(response)

# def test_view(request):
#     if request.method == "GET":
#         template_name = ""

class GameHistory(ListView):
    model = Game
    template_name = "game/game_list.html"
    context_object_name = "game_list"
    queryset = Game.objects.order_by('-score')

class PlayerHistory(ListView):
    model = Game
    template_name = "game/player_list.html"
    context_object_name = "game_list"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user = self.kwargs['id'])


class GamePlay(TemplateView):
    template_name = "game/breakout_clone.html"

game_website1_1/views.py
from django.views.generic.base import TemplateView


class Homepage(TemplateView):
    template_name = "index.html"

class Logout(TemplateView):
    template_name = "registration/logged_out.html"

posts/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, DetailView, ListView
from django.urls import reverse_lazy

from .models import Posts
from .forms import PostForm

# Create your views here.
class PostListView(ListView):
    template_name = 'post_list.html'
    model = Posts
    context_object_name = 'post_list'
    queryset = Posts.objects.all()


class PostCreateView(CreateView):
    template_name = 'post_create.html'
    model = Posts
    form_class = PostForm


    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}

    Sign Up

{% endblock %}


{% block content %}

    <h2>Sign Up</h2>
    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Sign Up</button>


    </form>

{% endblock %}

game/templates/game/breakout_clone.html
{% extends 'base.html' %}
{% load static %}

{% block css %}

    <link rel="stylesheet" href="{% static 'game/css/game.css' %}">

{% endblock %}

{% block content %}
    <body>

    <canvas id="myCanvas" width="480" height="320"></canvas>

    <div class="container">
        <div class="row">
            <div class="col text-center">
                <button class="btn btn-primary" id="game_history_button" data-url="{% url 'game:player_history' user.id %}" data-score = "{% url 'game:record_score' %}">Previous Scores</button>
                <h1 id="score"></h1>
            </div>


        </div>

    </div>


    </body>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="{% static 'game/js/breakout_clone.js' %}"></script>

{% endblock %}

game/templates/game/game_list.html
{% extends 'base.html' %}


{% block title %}

    Rankings

{% endblock %}

{% block content %}

    <h1>Rankings</h1>


    <table class="table">
        <thead>
            <tr>
                <th scope="col">Rank</th>
                <th scope="col">Username</th>
                <th scope="col">Score</th>
                <th scope="col">Time</th>
            </tr>
        </thead>

    {% for game in game_list %}

        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ game.user }}</td>
            <td>{{ game.score }}</td>
            <td>{{ game.time }}</td>
        </tr>


    {% endfor %}
    </table>

{% endblock %}

game/templates/game/game_play.html
{% extends 'base.html' %}
{% load static %}

{% block title %}

    Game Play

{% endblock %}


{% block content %}



    <h1>Your Score is Below:</h1>

    <h2 id="number">###</h2>



    <button id="game_history_button" data-url="{% url 'game:game_history' %}" data-score = "{% url 'game:record_score' %}">Go to Game History</button>


{% endblock %}

{% block scripts %}

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="{% static 'game/js/game.js' %}"></script>

{% endblock %}

game/templates/game/player_list.html
{% extends 'base.html' %}


{% block title %}

    Rankings

{% endblock %}

{% block content %}

    <h1>Previous Games</h1>


    <table class="table">
        <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">Score</th>
                <th scope="col">Time</th>
            </tr>
        </thead>

    {% for game in game_list %}

        <tr>
            <td>{{ game.user }}</td>
            <td>{{ game.score }}</td>
            <td>{{ game.time }}</td>
        </tr>


    {% endfor %}
    </table>

{% endblock %}

posts/templates/post_create.html
{% extends 'base.html' %}


{% block title %}

    Create Post

{% endblock %}


{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">

    </form>


{% endblock %}

posts/templates/post_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

posts/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

posts/templates/post_list.html
{% extends 'base.html' %}

{% block title %}

    Post List

{% endblock %}

{% block content %}

    <h1>Post List</h1>

    <table>

        <tr>
            <th>Post Title</th>
        </tr>

    {% for post in post_list %}

        <tr>
            <td>{{ post.title }}</td>
        </tr>

    {% endfor %}

    </table>



{% endblock %}

posts/templates/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Squada+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    {% block css %}{% endblock %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home' %}">Paddle and Ball</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>


        {% if user.is_authenticated %}

          <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link">Log Out</a>
          </li>
{#          <li class="nav-item">#}
{#                <a href="#" class="nav-link">Games</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#              <a class="nav-link" href="{% url 'posts:create_post' %}">Create Post</a>#}
{#          </li>#}
{#          <li class="nav-item">#}
{#              <a class="nav-link" href="{% url 'posts:post_list' %}">Post List</a>#}
{#          </li>#}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'game:game_history' %}">Rankings</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'game:game_play' %}">Play Game</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'game:player_history' user.id %}">Previous Scores</a>
          </li>


        {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          </li>

        {% endif %}



          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col col-sm-3 left">
                {% block right%}

                {% endblock %}
            </div>

            <div class="col col-sm-6">
                {% block content %}

                {% endblock %}
            </div>
            <div class="col col-sm-3 right">

                {% block left %}

                {% endblock %}

            </div>
        </div>
    </div>


</body>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


{% block scripts %}

{% endblock %}


</html>

templates/index.html
{% extends 'base.html' %}


{% block title %}

    Paddle and Ball

{% endblock %}

{% block content %}

    <div class="home_main_text">

    {% if user.is_authenticated %}

        <h1>Welcome Back!</h1>
        <h2>Play a <a href="{% url 'game:game_play' %}">Game</a>!</h2>

    {% else %}

        <h1 class="home_big_text">Welcome to the Paddle and Ball game website!</h1>
        <br><br>
        <h2 class="home_big_text">New Member? </h2><br>
        <h3 class="home_small_text"><a class="home_anchor" href="{% url 'accounts:signup' %}">Sign up</a> and start playing games!</h3>
        <br><br>
        <h2>Already Member? </h2>
        <h3><a class="home_anchor" href="{% url 'login' %}">Login</a> and start playing games!</h3>

    {% endif %}



    </div>



{% endblock %}